server:
  port: 18088
  tomcat:
    threads:
      max: 64
      min-spare: 16

spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.73.240:3306/test_db?characterEncoding=utf-8
    username: root
    password: 898421aA!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

management:
  security:
    enabled: false 